# All paths are relative to run.py.

# User-defined script for loading data. Must contain a function job_list(config)
job_script: ./configs/satellite-b/job_script.py

data:
  # Data node is configuration passed to user-defined job_list() function
  # that is in job_script.
  data_directory: ./data/raw/satellite-b/files
  n_years_max: null # Number of DataFrames for return. None => all DataFrames.
  satellites: null
  loo: false

# Job is set to the satellite name in job_script.py
job: null

parallel_jobs: false

base_dir: ./data/results/satellite-b
run_desc: Same as results-1 but using new code structure and computing _resid models

# device sets training parallelization using one of
#   null
#   cpu (default if device is null)
#   gpu (Linux/Windows)
#   mps (OS-X)
device: null

num_epochs: 1
n_reps: 1

models:
  - ols
  - nn_mimo
  - nn_mimo_resid
  - nn_miso
  - nn_miso_resid

inputs: [r, theta, phi, imfby, imfbz, vsw, nsw, ey, ey_avg]
outputs: [bx, by, bz]

# true => [None, **outputs]; null or no attribute => Only use all inputs
removed_inputs:
  - null

dtype: float32

train_fraction: 0.8

# Neural network hyperparameters
nn_class: NeuralNetworkOneLayer
num_epochs: 100
n_reps: 1
batch_size: 256
hidden_size: 16
activation: Tanh
optimizer: Adam
optimizer_kwargs:
  lr: 0.01
