base_config: ./configs/satellite-b/base.yaml
run_desc: Same as run-0-cluster, but use Two-Layer NN.
parallel_jobs: false
data:
  satellites:
    - cluster1

nn:
  n_epochs: 100
  nn_class: NeuralNetworkTwoLayer
  hidden_size: 32
  activation: ReLU

models:
  - ols
  - nn_mimo
  - nn_mimo_resid
  - nn_miso
  - nn_miso_resid
