base_config: ./configs/satellite-b/base.yaml
run_desc: Run only cluster1.
parallel_jobs: false
data:
  satellites:
    - cluster1
  n_years_max: 3

lags: 0

models:
  - ols
  - nn_miso

nn:
  n_epochs: 2
  nn_class: NeuralNetworkOneLayer
  hidden_size: 32
  activation: ReLU

