base_config: ./configs/satellite-b/base.yaml
run_desc: Run all satellites.
parallel_jobs: false

nn:
  n_epochs: 2
  nn_class: NeuralNetworkOneLayer
  hidden_size: 32
  activation: ReLU

models:
  - ols
  - nn_mimo
