base_config: ./configs/satellite-b/base.yaml
run_dir: ./data/results/satellite-b/serial
run_desc: Use parallel_jobs = false and do a single job for cluster1
data:
  satellites: cluster1
  n_years_max: null
  loo: false
parallel_jobs: true
device: mps
num_epochs: 100
num_boot_reps: 1
removed_inputs:
  - null
models:
  - ols
  - nn_mimo
  - nn_mimo_resid
  - nn_miso
  - nn_miso_resid

