# All paths are relative to main.py.

# User-defined script for loading data. Must contain a function job_list(config)
job_script: ./configs/demo/job_script.py

# The following are set in demo-0.yaml
data:

job: null

run_dir: 
run_desc: 

parallel_jobs: false

# device sets training parallelization using one of
#   null
#   cpu (default if device is null)
#   gpu (Linux/Windows)
#   mps (OS-X)
device: null

models:
  - ols
#  - nn_mimo
#  - nn_mimo_resid
#  - nn_miso
#  - nn_miso_resid

# True => [None, **outputs]; null or no attribute => Only use all inputs
removed_inputs: false
inputs: [input1]
outputs: [output1]

dtype: float32

train_fraction: 0.8

# Neural network hyperparameters
num_epochs: 2
num_boot_reps: 2
batch_size: 256
hidden_size: 32
activation: Tanh
optimizer: Adam
optimizer_kwargs:
  lr: 0.01
