# All paths are relative to run.py.
base_config: ./configs/demo/base.yaml
run_dir: demo-1
run_desc: Run contains three jobs, each with different noise equal to (job index) * noise_amplitude

data:
  noise_amplitude: 0.1
  # Number of jobs to run. If 3, noise_amplitudes will be [0, 1, num_jobs-1]/noise_amplitude
  num_jobs: 3
  cadence: "1s"
  # Quotes need for start/stop values to prevent automatic conversion to
  # datetime by Python YAML parser
  start: "2023-01-01"
  end: "2023-01-02"

