# All paths are relative to run.py.
base_config: ./configs/demo/base.yaml

data:
  noise_amplitude: 0.1
  num_jobs: 1
  cadence: "1s"
  # Quotes need for start/stop values to prevent automatic conversion to
  # datetime by Python YAML parser
  start: "2023-01-01"
  end: "2023-01-02"

run_dir: ./data/results/demo/demo-0
run_desc: Run contains three jobs, each with different noise equal to (job index) * noise_amplitude
